In [ ]:
import torch
print(torch.__version__)

2.4.1+cu121


# Introduction to Tensors
## Creating tensors
Pytorch tensors are created using `torch.Tensor()`

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim   # Scalar has no dimension

0

In [ ]:
scalar.item()   # Get tensor back as Python int -> a tensor with 2 or more elements cannot be converted to Scalar

7

In [ ]:
scalar.shape

torch.Size([])

----

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim   # Dimension is the number of square brackets

1

In [ ]:
vector.shape

torch.Size([2])

---

In [ ]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

----

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape   # shape는 각각의 bracket(dimansion) 안에 몇  개의 요소가 있느냐로 정의된다.

torch.Size([1, 3, 3])

## Random tensors
Why randon tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers.....`

In [18]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9239, 0.8270, 0.8382, 0.9021],
        [0.6410, 0.0402, 0.2870, 0.7511],
        [0.5030, 0.1987, 0.4213, 0.1465]])

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(224,224,3)    # height, width, channel
random_image_size_tensor

tensor([[[0.2734, 0.6411, 0.2488],
         [0.3042, 0.5214, 0.0932],
         [0.1402, 0.7596, 0.8776],
         ...,
         [0.9687, 0.9930, 0.9465],
         [0.3415, 0.1802, 0.4043],
         [0.0922, 0.7895, 0.6741]],

        [[0.4537, 0.9216, 0.4287],
         [0.5871, 0.0140, 0.9600],
         [0.9035, 0.1358, 0.3490],
         ...,
         [0.4037, 0.2168, 0.7714],
         [0.9161, 0.7621, 0.1923],
         [0.5744, 0.4938, 0.8375]],

        [[0.6901, 0.0456, 0.2671],
         [0.5916, 0.7978, 0.4498],
         [0.6890, 0.6285, 0.5999],
         ...,
         [0.8962, 0.4292, 0.2707],
         [0.7291, 0.5566, 0.2399],
         [0.6425, 0.8989, 0.8522]],

        ...,

        [[0.3506, 0.5755, 0.1447],
         [0.0892, 0.6163, 0.1877],
         [0.0925, 0.2451, 0.2783],
         ...,
         [0.7998, 0.4753, 0.6599],
         [0.1732, 0.5179, 0.2584],
         [0.1360, 0.9894, 0.4928]],

        [[0.0115, 0.4743, 0.8847],
         [0.1920, 0.0755, 0.4784],
         [0.