In [1]:
import torch
print(torch.__version__)

2.0.1+cu118


# Introduction to Tensors
## Creating tensors
Pytorch tensors are created using `torch.Tensor()`

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim   # Scalar has no dimension

0

In [4]:
scalar.item()   # Get tensor back as Python int -> a tensor with 2 or more elements cannot be converted to Scalar

7

In [5]:
scalar.shape

torch.Size([])

----

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim   # Dimension is the number of square brackets

1

In [8]:
vector.shape    # Shape is the number of elements of each square brackets

torch.Size([2])

---

In [9]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

----

In [12]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape   # shape는 각각의 bracket(dimansion) 안에 몇  개의 요소가 있느냐로 정의된다.

torch.Size([1, 3, 3])

## Random tensors
Why randon tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers.....`

In [15]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9667, 0.8447, 0.9420, 0.9485],
        [0.3980, 0.6571, 0.6869, 0.4383],
        [0.5144, 0.3535, 0.7889, 0.8462]])

In [16]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(224,224,3)    # height, width, channel
random_image_size_tensor

tensor([[[0.3372, 0.3301, 0.3086],
         [0.1654, 0.6810, 0.3374],
         [0.9536, 0.3761, 0.5112],
         ...,
         [0.2486, 0.2138, 0.2916],
         [0.2538, 0.6024, 0.0536],
         [0.9148, 0.9891, 0.1178]],

        [[0.9064, 0.3815, 0.1110],
         [0.2610, 0.0445, 0.3244],
         [0.1231, 0.0759, 0.4260],
         ...,
         [0.9266, 0.7186, 0.5547],
         [0.6218, 0.1941, 0.1473],
         [0.5506, 0.7822, 0.9083]],

        [[0.0134, 0.7411, 0.6296],
         [0.1803, 0.0419, 0.5088],
         [0.2554, 0.3374, 0.7887],
         ...,
         [0.4339, 0.8293, 0.5806],
         [0.6563, 0.1303, 0.8198],
         [0.8800, 0.4294, 0.7863]],

        ...,

        [[0.9522, 0.3679, 0.1692],
         [0.6311, 0.9511, 0.5069],
         [0.6791, 0.4304, 0.3226],
         ...,
         [0.1899, 0.8201, 0.8132],
         [0.4059, 0.4402, 0.9717],
         [0.4501, 0.0794, 0.8881]],

        [[0.2311, 0.8966, 0.2800],
         [0.0842, 0.0450, 0.8001],
         [0.

## Zeros and ones
`torch.zeros()` and `torch.ones()` and `torch.rand()` are all torch.float32 type

In [17]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones = torch.ones(1,3,3)
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [19]:
zeros.dtype

torch.float32

In [20]:
ones.dtype

torch.float32

In [21]:
random_tensor.dtype

torch.float32

In [22]:
scalar.dtype

torch.int64

In [23]:
vector.dtype

torch.int64

In [24]:
MATRIX.dtype

torch.int64

In [25]:
TENSOR.dtype

torch.int64

## Creating a range of tensors and tensors-like
`torch.arange()` is similar with range in python. `torch.zeros_like()` makes a tensor with zeros in the same shape of input.

In [26]:
zero_to_nine = torch.arange(10)    # similar with range in python 
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
zero_to_nine.shape

torch.Size([10])

In [28]:
ten_zeros = torch.zeros_like(input = zero_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Getting information from tensors
the default datatype of tensors is `torch.float32`    
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch
1. Tensors not right datatype `tensor.dtype`
2. Tensors not right shape `tensor.shape` = `tensor.size()`
3. Tensors not on the right device `tensor.device`

In [47]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,    # what datatype is the tensor (ex. float32, float16)
                              device='cpu',    # what device is your tensor on. cpu by default
                              requires_grad=False)   # whether or not track gradients with this tensors operations    
float_32_tensor.dtype

torch.float32

In [40]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [41]:
tensor_operated = float_32_tensor * float_16_tensor
print(tensor_operated)
print(tensor_operated.dtype)

tensor([ 9., 36., 81.])
torch.float32


In [42]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [43]:
tensor_operated = float_32_tensor * int_32_tensor
print(tensor_operated)
print(tensor_operated.dtype)

tensor([ 9., 36., 81.])
torch.float32


In [45]:
long_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
long_tensor

tensor([3, 6, 9])

In [46]:
tensor_operated = float_32_tensor * long_tensor
print(tensor_operated)
print(tensor_operated.dtype)

tensor([ 9., 36., 81.])
torch.float32


### Manipulating Tensors
Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimentions** must match
2. The resulting matrix has the shape of the **outer dimensions**

In [49]:
tensor = torch.tensor([1,2,3])
tensor + 10    # Does not resign the tensor

tensor([11, 12, 13])

In [50]:
tensor * 10

tensor([10, 20, 30])

In [51]:
tensor - 10

tensor([-9, -8, -7])

In [55]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [53]:
torch.add(tensor, 10)    # Pytorch in-built functions

tensor([11, 12, 13])

In [52]:
torch.mul(tensor, 10)   

tensor([10, 20, 30])

In [54]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [57]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [58]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [59]:
# Matrix multiplication (dot product)
torch.matmul(tensor, tensor)

tensor(14)

In [60]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.    
A **transpose** switches the axes or dimentions of a given tensor.

In [61]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
torch.mm(tensor_A, tensor_B)    # the same as torch.matmul (it's an alias)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [62]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [65]:
tensor_A @ tensor_B.T

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [66]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [69]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [70]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [72]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [73]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [74]:
x.argmin()

tensor(0)

In [75]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping: reshapes an input tensor to a definded shape
* View: Retrun a view of an input tensor of certain shape but **keep the same memory as the original tensor** 
* Stacking: combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze: removes all `1` dimensions from a tensor
* Unsqueeze: add a `1` dimensions to a target tensor
* Permute: Return a view of the input with dimensions permuted (swapped) in a certain way

In [2]:
x = torch.arange(1,10)
x, x.shape, x.ndim

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]), 1)

In [3]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]), 2)

In [4]:
z = x.view(3,3)
z, z.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [5]:
z[:,0] = 5    # a view of tensor shares the same memory as the original
z, x

(tensor([[5, 2, 3],
         [5, 5, 6],
         [5, 8, 9]]),
 tensor([5, 2, 3, 5, 5, 6, 5, 8, 9]))

In [6]:
x[0] = 0
z, x

(tensor([[0, 2, 3],
         [5, 5, 6],
         [5, 8, 9]]),
 tensor([0, 2, 3, 5, 5, 6, 5, 8, 9]))

In [8]:
x.ndim

1

In [15]:
x_stacked = torch.stack([x,x,x,x], dim=0)    # only until x ndim limits
x_stacked, x_stacked.shape, x_stacked.ndim

(tensor([[0, 2, 3, 5, 5, 6, 5, 8, 9],
         [0, 2, 3, 5, 5, 6, 5, 8, 9],
         [0, 2, 3, 5, 5, 6, 5, 8, 9],
         [0, 2, 3, 5, 5, 6, 5, 8, 9]]),
 torch.Size([4, 9]),
 2)

In [16]:
x_stacked = torch.stack([x,x,x,x], dim=1)    # only until x ndim limits
x_stacked, x_stacked.shape, x_stacked.ndim

(tensor([[0, 0, 0, 0],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [5, 5, 5, 5],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [5, 5, 5, 5],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]),
 torch.Size([9, 4]),
 2)

In [10]:
z.ndim

2

In [20]:
z

tensor([[0, 2, 3],
        [5, 5, 6],
        [5, 8, 9]])

In [17]:
z_stacked = torch.stack([z,z,z,z], dim=0)    # dim으로 지정된 차원의 것을 똑같이 쌓는다고 생각.
z_stacked, z_stacked.shape, z_stacked.ndim

(tensor([[[0, 2, 3],
          [5, 5, 6],
          [5, 8, 9]],
 
         [[0, 2, 3],
          [5, 5, 6],
          [5, 8, 9]],
 
         [[0, 2, 3],
          [5, 5, 6],
          [5, 8, 9]],
 
         [[0, 2, 3],
          [5, 5, 6],
          [5, 8, 9]]]),
 torch.Size([4, 3, 3]),
 3)

In [18]:
z_stacked = torch.stack([z,z,z,z], dim=1)
z_stacked, z_stacked.shape, z_stacked.ndim

(tensor([[[0, 2, 3],
          [0, 2, 3],
          [0, 2, 3],
          [0, 2, 3]],
 
         [[5, 5, 6],
          [5, 5, 6],
          [5, 5, 6],
          [5, 5, 6]],
 
         [[5, 8, 9],
          [5, 8, 9],
          [5, 8, 9],
          [5, 8, 9]]]),
 torch.Size([3, 4, 3]),
 3)

In [19]:
z_stacked = torch.stack([z,z,z,z], dim=2)
z_stacked, z_stacked.shape, z_stacked.ndim

(tensor([[[0, 0, 0, 0],
          [2, 2, 2, 2],
          [3, 3, 3, 3]],
 
         [[5, 5, 5, 5],
          [5, 5, 5, 5],
          [6, 6, 6, 6]],
 
         [[5, 5, 5, 5],
          [8, 8, 8, 8],
          [9, 9, 9, 9]]]),
 torch.Size([3, 3, 4]),
 3)

In [21]:
x_reshaped

tensor([[0, 2, 3, 5, 5, 6, 5, 8, 9]])

In [22]:
x_reshaped.shape

torch.Size([1, 9])

In [25]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([0, 2, 3, 5, 5, 6, 5, 8, 9]), torch.Size([9]))

In [27]:
x_reshaped.unsqueeze(dim=0), x_reshaped.unsqueeze(dim=0).shape

(tensor([[[0, 2, 3, 5, 5, 6, 5, 8, 9]]]), torch.Size([1, 1, 9]))

In [30]:
x_reshaped.unsqueeze(dim=1), x_reshaped.unsqueeze(dim=1).shape

(tensor([[[0, 2, 3, 5, 5, 6, 5, 8, 9]]]), torch.Size([1, 1, 9]))

In [31]:
x_reshaped.unsqueeze(dim=2), x_reshaped.unsqueeze(dim=2).shape

(tensor([[[0],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]]]),
 torch.Size([1, 9, 1]))

In [34]:
# torch.permute: rearranges the dimensions of a target tensor in a specified order
# permuted: same memory with original!!
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

In [35]:
x_original[0,0,0] = 7
x_original[0,0,0], x_permuted[0,0,0]

(tensor(7.), tensor(7.))

### Indexing(selecting data from tensors)

In [36]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [37]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
x[0,0], x[0][0], x[0,0,:]    # SAME!!

(tensor([1, 2, 3]), tensor([1, 2, 3]), tensor([1, 2, 3]))

In [40]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [41]:
# Get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [42]:
x[0, 1, 1]

tensor(5)

In [43]:
# Get index 0 of oth and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

### Pytorch tensors & numpy
* Data in Numpy -> Pytorch tensor: `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy: `torch.Tensor.numpy()`     
they don't share the memory

In [54]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)    # when converting from numpy -> default dtype: float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [55]:
tensor = tensor.type(torch.float32)    # We should convert default dtype of Pytorch
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [56]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out of random)
To reduce the randomness in neural networks and Pytorch comes the concept of a **random seed**.     
Essentially what the random seed does is "flavour" the randomness

In [58]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

random_tensor_A, random_tensor_B

(tensor([[0.1945, 0.4086, 0.8320, 0.0192],
         [0.6327, 0.9805, 0.8834, 0.7515],
         [0.5601, 0.8400, 0.9890, 0.7195]]),
 tensor([[0.4450, 0.7223, 0.5153, 0.4291],
         [0.4805, 0.5462, 0.2975, 0.2835],
         [0.4313, 0.8288, 0.5965, 0.6009]]))

In [59]:
random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [60]:
RANDOM_SEED = 123
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)    # each time!
random_tensor_D = torch.rand(3,4)

random_tensor_C, random_tensor_D

(tensor([[0.2961, 0.5166, 0.2517, 0.6886],
         [0.0740, 0.8665, 0.1366, 0.1025],
         [0.1841, 0.7264, 0.3153, 0.6871]]),
 tensor([[0.2961, 0.5166, 0.2517, 0.6886],
         [0.0740, 0.8665, 0.1366, 0.1025],
         [0.1841, 0.7264, 0.3153, 0.6871]]))

In [61]:
random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running tensors and Pytorch objects on the GPUs (and making faster computations)

In [63]:
# Check for GPU access with Pytorch
torch.cuda.is_available()

True

In [64]:
# setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [65]:
torch.cuda.device_count()

1

In [67]:
tensor = torch.tensor([1,2,3])
tensor.device    # default is cpu

device(type='cpu')

In [68]:
tensor_in_gpu = tensor.to(device)
tensor_in_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [69]:
tensor_in_gpu.numpy()    # numpy can't run in GPU

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [72]:
tensor_in_cpu = tensor_in_gpu.cpu()
tensor_in_cpu

tensor([1, 2, 3])

In [73]:
tensor_in_cpu.device

device(type='cpu')

In [74]:
tensor_in_cpu.numpy()

array([1, 2, 3], dtype=int64)