numpy-ndarray

In [1]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print('ndim: ', n_array.ndim, 'shape: ', n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim:  2 shape:  (2, 5)


pytorch-tensor

In [2]:
import torch
t_array = torch.FloatTensor(n_array)    # array to tensor
print(t_array)
print('ndim: ', t_array.ndim, 'shape: ', t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim:  2 shape:  torch.Size([2, 5])


numpy like operations

In [4]:
data = [[3,5,20],[10,5,50],[1,5,10]]
x_data = torch.tensor(data)

In [6]:
x_data

tensor([[ 3,  5, 20],
        [10,  5, 50],
        [ 1,  5, 10]])

In [5]:
x_data[1:]    # slicing

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [7]:
x_data[:2, 1:]

tensor([[ 5, 20],
        [ 5, 50]])

In [8]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [9]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [10]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]], dtype=int64)

In [11]:
x_data.shape

torch.Size([3, 3])

In [12]:
x_data.dtype

torch.int64

In [13]:
x_data.device    

device(type='cpu')

In [19]:
if torch.cuda.is_available():    # pytorch의 tensor는 GPU에 올려 사용 가능
    x_data = x_data.to('cuda')
x_data.device

device(type='cpu')

- view: reshape과 동일하게 tensor의 shape를 변환
- squeeze: 차원의 개수가 1인 차원을 삭제(압축)
- unsqueeze: 차원의 개수가 1인 차원을 추가

In [21]:
tensor_ex = torch.rand(size=(2,3,2))    # 2*3*2=12
tensor_ex

tensor([[[0.4189, 0.2398],
         [0.8404, 0.5741],
         [0.5482, 0.9049]],

        [[0.9135, 0.0830],
         [0.9941, 0.5273],
         [0.2961, 0.5993]]])

In [22]:
tensor_ex.view([-1,6])     # 2*6=12

tensor([[0.4189, 0.2398, 0.8404, 0.5741, 0.5482, 0.9049],
        [0.9135, 0.0830, 0.9941, 0.5273, 0.2961, 0.5993]])

In [24]:
tensor_ex.reshape([-1,6])

tensor([[0.4189, 0.2398, 0.8404, 0.5741, 0.5482, 0.9049],
        [0.9135, 0.0830, 0.9941, 0.5273, 0.2961, 0.5993]])

In [41]:
# view와 reshape의 차이가 엄밀히 존재하긴 하지만, 대부분의 경우 view를 쓰면 문제없다.
a = torch.zeros(3,2)
b = a.view(2,3)
c = a.t().reshape(6)

In [42]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [43]:
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [44]:
c

tensor([0., 0., 0., 0., 0., 0.])

In [45]:
a.fill_(1)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [46]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [47]:
c

tensor([0., 0., 0., 0., 0., 0.])

In [14]:
tensor_ex1 = torch.rand(size=(1,2,2))
tensor_ex1

tensor([[[0.8496, 0.1673],
         [0.0734, 0.1979]]])

In [18]:
tensor_ex1_sq = tensor_ex1.squeeze()
tensor_ex1_sq    # squeeze()는 차원의 갯수가 1인 차원을 삭제한 텐서를 반환

tensor([[0.8496, 0.1673],
        [0.0734, 0.1979]])

In [19]:
tensor_ex1_sq.size()

torch.Size([2, 2])

In [11]:
tensor_ex2 = torch.rand(size=(2,1,2))
tensor_ex2

tensor([[[0.2352, 0.6890]],

        [[0.9145, 0.3719]]])

In [20]:
tensor_ex2.squeeze_()    # squeeze_()는 차원의 갯수가 1인 차원을 삭제

tensor([[0.2352, 0.6890],
        [0.9145, 0.3719]])

In [22]:
tensor_ex2.size()

torch.Size([2, 2])

In [23]:
tensor_ex3 = torch.rand(size=(2,2,1))
tensor_ex3

tensor([[[0.3870],
         [0.5295]],

        [[0.2297],
         [0.9115]]])

In [24]:
tensor_ex3.squeeze().size()

torch.Size([2, 2])

In [27]:
tensor_ex = torch.rand(size=(2,2))
tensor_ex

tensor([[0.4804, 0.8486],
        [0.6089, 0.3153]])

In [28]:
tensor_ex.unsqueeze(0)

tensor([[[0.4804, 0.8486],
         [0.6089, 0.3153]]])

In [30]:
tensor_ex.unsqueeze(0).size()

torch.Size([1, 2, 2])

In [31]:
tensor_ex.unsqueeze(1).shape

torch.Size([2, 1, 2])

In [32]:
tensor_ex.unsqueeze(2).shape

torch.Size([2, 2, 1])

In [33]:
tensor_ex4 = torch.rand(size=(1,2,3,4))
tensor_ex4

tensor([[[[0.1027, 0.0990, 0.9774, 0.7732],
          [0.3812, 0.1678, 0.2719, 0.0853],
          [0.1931, 0.0137, 0.0478, 0.8099]],

         [[0.1289, 0.5693, 0.4581, 0.1762],
          [0.7796, 0.8426, 0.9546, 0.3393],
          [0.1778, 0.5082, 0.3323, 0.5022]]]])

In [34]:
tensor_ex4.squeeze_()

tensor([[[0.1027, 0.0990, 0.9774, 0.7732],
         [0.3812, 0.1678, 0.2719, 0.0853],
         [0.1931, 0.0137, 0.0478, 0.8099]],

        [[0.1289, 0.5693, 0.4581, 0.1762],
         [0.7796, 0.8426, 0.9546, 0.3393],
         [0.1778, 0.5082, 0.3323, 0.5022]]])

행렬곱셈 연산은 dot이 아닌 mm(matmul) 함수 사용!    
dot은 벡터 연산용

In [43]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)

In [44]:
t1 = torch.FloatTensor(n1)
t1

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [45]:
t2 = torch.FloatTensor(n2)
t2

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [46]:
t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [47]:
t1.dot(t2)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [48]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

mm은 broadcasting을 지원하지 않고, matmul은 broadcasting을 지원한다는 차이

In [49]:
a = torch.rand(5,2,3)
b = torch.rand(3)
a.mm(b)

RuntimeError: self must be a matrix

In [50]:
a.matmul(b)

tensor([[0.4257, 0.5425],
        [0.8093, 0.9252],
        [1.0978, 0.7917],
        [1.2068, 1.2484],
        [1.3038, 0.1957]])