In [1]:
import torch

### Collocation Points

In [2]:
def collocation_points(*args):
    grids = torch.meshgrid(*args, indexing = 'ij')
    coordinates = torch.stack(grids, dim = len(args)).reshape(-1, len(args))
    return coordinates

In [3]:
# t, x만 존재 -> 1차원
nt = 3
nx = 3
t = torch.linspace(0, 1 , nt)    # 시간 단위 0~1까지
x = torch.linspace(-1, 1, nx)    # 공간 단위 -1~1까지

In [4]:
t

tensor([0.0000, 0.5000, 1.0000])

In [5]:
x

tensor([-1.,  0.,  1.])

In [6]:
cdata = collocation_points(t, x)
cdata

tensor([[ 0.0000, -1.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  1.0000],
        [ 0.5000, -1.0000],
        [ 0.5000,  0.0000],
        [ 0.5000,  1.0000],
        [ 1.0000, -1.0000],
        [ 1.0000,  0.0000],
        [ 1.0000,  1.0000]])

In [7]:
cdata.shape

torch.Size([9, 2])

In [10]:
ny = 3
y = torch.linspace(-1, 1, ny)
cdata = collocation_points(t, x, y)
print(f'{cdata.shape}\n{cdata}')

torch.Size([27, 3])
tensor([[ 0.0000, -1.0000, -1.0000],
        [ 0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000,  1.0000],
        [ 0.0000,  0.0000, -1.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  1.0000],
        [ 0.0000,  1.0000, -1.0000],
        [ 0.0000,  1.0000,  0.0000],
        [ 0.0000,  1.0000,  1.0000],
        [ 0.5000, -1.0000, -1.0000],
        [ 0.5000, -1.0000,  0.0000],
        [ 0.5000, -1.0000,  1.0000],
        [ 0.5000,  0.0000, -1.0000],
        [ 0.5000,  0.0000,  0.0000],
        [ 0.5000,  0.0000,  1.0000],
        [ 0.5000,  1.0000, -1.0000],
        [ 0.5000,  1.0000,  0.0000],
        [ 0.5000,  1.0000,  1.0000],
        [ 1.0000, -1.0000, -1.0000],
        [ 1.0000, -1.0000,  0.0000],
        [ 1.0000, -1.0000,  1.0000],
        [ 1.0000,  0.0000, -1.0000],
        [ 1.0000,  0.0000,  0.0000],
        [ 1.0000,  0.0000,  1.0000],
        [ 1.0000,  1.0000, -1.0000],
        [ 1.0000,  1.0000,  0.0000],
        [ 1.0000, 

### Initial Condition

In [12]:
u0 = torch.sin(x)    # 지배함수를 sin이라고 가정, 각각의 nx에서의 값
inidata = collocation_points(t[0], x)    # initial -> t = 0

In [14]:
u0

tensor([-0.8415,  0.0000,  0.8415])

In [13]:
inidata

tensor([[ 0., -1.],
        [ 0.,  0.],
        [ 0.,  1.]])

### Boundary Condition

In [16]:
xbg = torch.FloatTensor([x[0], x[-1]])
xbg

tensor([-1.,  1.])

In [17]:
bgdata = collocation_points(t, xbg)

In [18]:
bgdata

tensor([[ 0.0000, -1.0000],
        [ 0.0000,  1.0000],
        [ 0.5000, -1.0000],
        [ 0.5000,  1.0000],
        [ 1.0000, -1.0000],
        [ 1.0000,  1.0000]])

### Data Loader
: 배치 트레이닝을 하기 위해, 데이터를 나눠서 주는 과정 -> Data Loader로 구현

In [19]:
class TensorData(torch.utils.data.Dataset):
    def __init__(self, cdata):
        self.cdata = cdata
        self.len = len(cdata)
        
    def __getitem__(self, index):
        return self.cdata[index]
    
    def __len__(self):
        return self.len

In [ ]:
batch_size = 8
trainloader = torch.utils.data.DataLoader(Ten)